name: penguins
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
        
      - name: Do the job!
        run: |
          Rscript Untitled.R
